name: Build and Run Apptainer

on:
  workflow_dispatch:  # Allows manual triggering


jobs:
  apptainer:
    runs-on: ubuntu-20.04  # Set the GitHub Actions runner to Ubuntu 20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential squashfs-tools cryptsetup
          git clone https://github.com/apptainer/apptainer.git
          cd apptainer
          make -C builddir
          sudo make -C builddir install

      - name: Build Apptainer container
        run: apptainer build my_container.sif Buildfile

      - name: Run Apptainer container
        run: apptainer exec my_container.sif python3 --version


